version = 3.10.0
runner.dialect = scala3
maxColumn = 120
project.git = false
project.includePaths = [
  "glob:**.sbt",
  "glob:**/Factorizations.scala",
  "glob:**/Workspace.scala",
  "glob:**/PivotedQRScreenSuite.scala",
  "glob:**/PublishedInteropConsumer.scala"
]
