package gale.golden

import gale.linalg.*
import gale.sparse.SparseVector
import gale.spectral.*

import scala.collection.mutable

/** Replays the Breeze 2.1.0 golden corpus ([[BreezeGoldens]]) through gale's public API on the JVM and on
  * Scala.js. This is gale's only external-reference check of its Scala.js numerics; Breeze itself is JVM-only, so
  * the references are generated by `sbt breezeGoldens` (see `parity/README.md`).
  *
  * '''Tolerance policy.''' Never bit-exact: gale and Breeze use different algorithms and summation orders, and on
  * Scala.js `PlatformMath.fma` is `a*b+c`. Each comparison computes an error ''unit'' with the shape of the
  * standard forward-error bound, `n · κ · ε · scale` (`ε = 2⁻⁵²`; `κ` is Breeze's 2-norm condition number where
  * the result is conditioning-sensitive, `1` for backward-stable products and reductions), and asserts
  * `|gale − breeze| ≤ C · unit` with one constant [[C]]. Operations that are exact or correctly rounded in both
  * libraries (max/min/argmax, `normInf`, `kron`, sparse `+`/`−`) have unit `0` and must match exactly.
  * Eigenvectors are compared through cluster projectors with unit `n ε ‖A‖ / gap`. The worst observed
  * `error / unit` per family is printed after the suite.
  */
class BreezeGoldenSuite extends munit.FunSuite:

  /** The single tolerance constant multiplying every error unit. */
  private val C = 8.0

  private val Eps = Math.ulp(1.0)

  private val worst = mutable.LinkedHashMap.empty[String, (Double, String)]

  override def afterAll(): Unit =
    val platform = if System.getProperty("java.vm.name", "").contains("Scala.js") then "JS" else "JVM"
    println(s"BreezeGoldenSuite ($platform) worst error / unit by family and output (bound C = $C):")
    worst.toSeq.sortBy(_._1).foreach { case (k, (r, at)) => println(f"  $k%-28s $r%10.4f  ($at)") }

  // ---------------------------------------------------------------------------
  // Comparison helpers
  // ---------------------------------------------------------------------------

  private def check(c: GoldenCase, output: String, ratio: Double): Unit =
    val key = s"${c.family}/$output"
    if !worst.get(key).exists(_._1 >= ratio) then worst(key) = (ratio, c.name)
    assert(ratio <= C, s"${c.name}/$output: error is $ratio units (bound $C)")

  /** Worst `|g_i − ref_i| / unit(i)`; an exact match is `0` even when the unit is `0` or the value infinite. */
  private def ratio(g: Array[Double], ref: Array[Double], unit: Int => Double): Double =
    assertEquals(g.length, ref.length)
    var worstRatio = 0.0
    var i = 0
    while i < g.length do
      if g(i) != ref(i) then
        val r = math.abs(g(i) - ref(i)) / unit(i)
        worstRatio = if r.isNaN then Double.PositiveInfinity else math.max(worstRatio, r)
      i += 1
    worstRatio

  private def ratio(g: Double, ref: Double, unit: Double): Double = ratio(Array(g), Array(ref), _ => unit)

  private def mat(a: GoldenArray): DMat = Matrix.tabulate(a.rows, a.cols)((i, j) => a(i, j))
  private def vec(a: Array[Double]): DVec = Vec.tabulate(a.length)(a(_))
  private def arr(v: DVec): Array[Double] = Array.tabulate(v.length)(v(_))
  private def arr(m: DMat): Array[Double] = Array.tabulate(m.rows * m.cols)(k => m(k / m.cols, k % m.cols))
  private def maxAbs(a: Array[Double]): Double = a.foldLeft(0.0)((s, x) => math.max(s, math.abs(x)))
  private def sumAbs(a: Array[Double]): Double = a.foldLeft(0.0)((s, x) => s + math.abs(x))

  /** `max_i Σ_k |a_ik| |b_kj|` over all output entries: the scale of a rounding-error bound for `A B`. */
  private def absProductMax(a: GoldenArray, b: GoldenArray, transposeA: Boolean): Double =
    val (m, k) = if transposeA then (a.cols, a.rows) else (a.rows, a.cols)
    var out = 0.0
    for i <- 0 until m; j <- 0 until b.cols do
      var s = 0.0
      for p <- 0 until k do s += math.abs(if transposeA then a(p, i) else a(i, p)) * math.abs(b(p, j))
      out = math.max(out, s)
    out

  private def kappa(c: GoldenCase): Double = c.scalar("kappa")

  // ---------------------------------------------------------------------------
  // Replay, one test per golden case
  // ---------------------------------------------------------------------------

  private val families = Set(
    "matvec",
    "matmul",
    "vector",
    "lu",
    "cholesky",
    "qr",
    "eigsym",
    "svd",
    "pinv",
    "kron",
    "reduce-vector",
    "reduce-matrix",
    "numerics",
    "sparse"
  )

  test("the golden corpus is non-empty and every family is known") {
    assert(BreezeGoldens.cases.nonEmpty)
    assertEquals(BreezeGoldens.cases.map(_.name).distinct.size, BreezeGoldens.cases.size)
    BreezeGoldens.cases.foreach(c => assert(families(c.family), s"unknown family ${c.family}"))
    assertEquals(BreezeGoldens.cases.map(_.family).toSet, families)
  }

  BreezeGoldens.cases.foreach(c => test(c.name)(replay(c)))

  private def replay(c: GoldenCase): Unit = c.family match
    case "matvec"        => matvec(c)
    case "matmul"        => matmul(c)
    case "vector"        => vector(c)
    case "lu"            => lu(c)
    case "cholesky"      => cholesky(c)
    case "qr"            => qr(c)
    case "eigsym"        => eigsym(c)
    case "svd"           => svd(c)
    case "pinv"          => pinv(c)
    case "kron"          => kron(c)
    case "reduce-vector" => reduceVector(c)
    case "reduce-matrix" => reduceMatrix(c)
    case "numerics"      => numerics(c)
    case "sparse"        => sparse(c)
    case other           => fail(s"unknown family $other")

  private def matvec(c: GoldenCase): Unit =
    val a = c.array("A")
    val ga = mat(a)
    val x = c.array("x")
    val xt = c.array("xt")
    val unitAx = a.cols * Eps * absProductMax(a, x, transposeA = false)
    check(c, "Ax", ratio(arr(ga * vec(x.values)), c.values("Ax"), _ => unitAx))
    val unitAtx = a.rows * Eps * absProductMax(a, xt, transposeA = true)
    check(c, "Atx", ratio(arr(ga.t * vec(xt.values)), c.values("Atxt"), _ => unitAtx))

  private def matmul(c: GoldenCase): Unit =
    val a = c.array("A")
    val b = c.array("B")
    val d = c.array("D")
    val unitAB = a.cols * Eps * absProductMax(a, b, transposeA = false)
    check(c, "AB", ratio(arr(mat(a) * mat(b)), c.values("AB"), _ => unitAB))
    val unitAtD = a.rows * Eps * absProductMax(a, d, transposeA = true)
    check(c, "AtD", ratio(arr(mat(a).t * mat(d)), c.values("AtD"), _ => unitAtD))

  private def vector(c: GoldenCase): Unit =
    val x = c.values("x")
    val y = c.values("y")
    val alpha = c.scalar("alpha")
    val n = x.length
    val dotUnit = n * Eps * x.indices.map(i => math.abs(x(i) * y(i))).sum
    check(c, "dot", ratio(vec(x).dot(vec(y)), c.scalar("dot"), dotUnit))
    val gy = vec(y).mutableCopy
    gy.axpyInPlace(alpha, vec(x))
    check(c, "axpy", ratio(arr(gy.asVec), c.values("axpy"), i => Eps * (math.abs(alpha * x(i)) + math.abs(y(i)))))

  private def lu(c: GoldenCase): Unit =
    val a = c.array("A")
    val n = a.rows
    val ga = mat(a)
    val k = kappa(c)
    val x = c.values("x")
    check(c, "solve", ratio(arr(ga.solve(vec(c.values("b"))).orThrow), x, _ => n * k * Eps * maxAbs(x)))
    val det = c.scalar("det")
    check(c, "det", ratio(ga.det.orThrow, det, n * k * Eps * math.abs(det)))
    if c.has("inv") then
      val inv = c.values("inv")
      check(c, "inv", ratio(arr(ga.solve(Matrix.eye(n)).orThrow), inv, _ => n * k * Eps * maxAbs(inv)))

  private def cholesky(c: GoldenCase): Unit =
    val a = c.array("A")
    val n = a.rows
    val k = kappa(c)
    val factor = mat(a).cholesky.orThrow
    val l = c.values("L")
    val gl = Array.tabulate(n * n)(p => if p % n <= p / n then factor.lower(p / n, p % n) else 0.0)
    check(c, "L", ratio(gl, l, _ => n * k * Eps * maxAbs(l)))
    val x = c.values("x")
    check(c, "solve", ratio(arr(factor.solve(vec(c.values("b"))).orThrow), x, _ => n * k * Eps * maxAbs(x)))

  private def qr(c: GoldenCase): Unit =
    val a = c.array("A")
    val n = a.cols
    val k = kappa(c)
    val r = c.values("R")
    val gr = mat(a).qr.r
    val signs = Array.tabulate(n)(i => if gr(i, i) < 0.0 then -1.0 else 1.0)
    val grn = Array.tabulate(n * n)(p => if p % n >= p / n then signs(p / n) * gr(p / n, p % n) else 0.0)
    check(c, "R", ratio(grn, r, _ => n * k * Eps * maxAbs(r)))
    // Least squares: forward error (κ + κ² ‖r‖ / (‖A‖ ‖x‖)) ε, with ‖A‖_F ≥ ‖A‖₂ (a tighter bound).
    val x = c.values("x")
    val normA = math.sqrt(a.values.map(v => v * v).sum)
    val normX = math.sqrt(x.map(v => v * v).sum)
    val growth = k + k * k * c.scalar("residual") / (normA * normX)
    val gx = arr(mat(a).leastSquares(vec(c.values("b"))).orThrow)
    check(c, "lstsq", ratio(gx, x, _ => n * growth * Eps * maxAbs(x)))

  private def eigsym(c: GoldenCase): Unit =
    val a = c.array("A")
    val n = a.rows
    val values = c.values("values")
    val withVectors = c.has("vectors")
    val mode = if withVectors then EigenVectors.Right else EigenVectors.ValuesOnly
    val d = Eigen.eigSymmetric(mat(a), EigenSelection.All, mode).orThrow
    val norm = math.max(maxAbs(values), Double.MinPositiveValue)
    check(c, "values", ratio(arr(d.eigenvalues), values, _ => n * Eps * norm))
    if withVectors then
      val ref = c.array("vectors")
      val gv = d.eigenvectors
      val clusters = clustersOf(values, 1e-8 * norm)
      for cl <- clusters do
        val gap = clusters
          .filter(_ != cl)
          .map(q => math.min(math.abs(values(q.head) - values(cl.last)), math.abs(values(q.last) - values(cl.head))))
          .minOption
          .getOrElse(norm)
        var diff = 0.0
        for i <- 0 until n; j <- 0 until n do
          var pg = 0.0
          var pr = 0.0
          for k <- cl do
            pg += gv(i, k) * gv(j, k)
            pr += ref(i, k) * ref(j, k)
          diff = math.max(diff, math.abs(pg - pr))
        check(c, "vectors", ratio(diff, 0.0, n * Eps * norm / gap))

  private def clustersOf(values: Array[Double], tol: Double): Vector[Range] =
    val out = Vector.newBuilder[Range]
    var start = 0
    for i <- 1 until values.length do
      if values(i) - values(i - 1) > tol then
        out += (start until i)
        start = i
    out += (start until values.length)
    out.result()

  private def svd(c: GoldenCase): Unit =
    val a = c.array("A")
    val sigma = c.values("sigma")
    val g = mat(a).svd.orThrow
    check(c, "sigma", ratio(arr(g.singularValues), sigma, _ => math.max(a.rows, a.cols) * Eps * sigma(0)))

  private def pinv(c: GoldenCase): Unit =
    val a = c.array("A")
    val p = c.values("P")
    val unit = math.max(a.rows, a.cols) * kappa(c) * Eps * maxAbs(p)
    check(c, "P", ratio(arr(mat(a).pinv.orThrow), p, _ => unit))

  private def kron(c: GoldenCase): Unit =
    check(c, "K", ratio(arr(mat(c.array("A")).kron(mat(c.array("B")))), c.values("K"), _ => 0.0))

  private def reduceVector(c: GoldenCase): Unit =
    val x = c.values("x")
    val n = x.length
    val v = vec(x)
    val s1 = sumAbs(x)
    check(c, "sum", ratio(v.sum, c.scalar("sum"), n * Eps * s1))
    check(c, "mean", ratio(v.mean, c.scalar("mean"), Eps * s1 + Eps * math.abs(c.scalar("mean"))))
    check(c, "max", ratio(v.max, c.scalar("max"), 0.0))
    check(c, "min", ratio(v.min, c.scalar("min"), 0.0))
    check(c, "argmax", ratio(v.argmax.toDouble, c.scalar("argmax"), 0.0))
    check(c, "argmin", ratio(v.argmin.toDouble, c.scalar("argmin"), 0.0))
    check(c, "norm1", ratio(v.norm1, c.scalar("norm1"), n * Eps * s1))
    check(c, "norm2", ratio(v.norm2, c.scalar("norm2"), n * Eps * c.scalar("norm2")))
    check(c, "normInf", ratio(v.normInf, c.scalar("normInf"), 0.0))

  private def reduceMatrix(c: GoldenCase): Unit =
    val a = c.array("A")
    val (m, n) = (a.rows, a.cols)
    val g = mat(a)
    val s1 = sumAbs(a.values)
    check(c, "sum", ratio(g.sum, c.scalar("sum"), m * n * Eps * s1))
    check(c, "mean", ratio(g.mean, c.scalar("mean"), Eps * s1 + Eps * math.abs(c.scalar("mean"))))
    check(c, "max", ratio(g.max, c.scalar("max"), 0.0))
    check(c, "min", ratio(g.min, c.scalar("min"), 0.0))
    val (i, j) = g.argmax
    check(c, "argmax", ratio(Array(i.toDouble, j.toDouble), Array(c.scalar("argmaxRow"), c.scalar("argmaxCol")), _ => 0.0))
    val f = c.scalar("frobenius")
    check(c, "frobenius", ratio(g.normFrobenius, f, m * n * Eps * f))
    check(c, "norm1", ratio(g.norm1, c.scalar("norm1"), m * Eps * c.scalar("norm1")))
    check(c, "normInf", ratio(g.normInf, c.scalar("normInf"), n * Eps * c.scalar("normInf")))

  private def numerics(c: GoldenCase): Unit =
    val x = c.values("x")
    val n = x.length
    val relative = (ref: Array[Double]) => (i: Int) => Eps * math.abs(ref(i))
    val exp = c.values("exp")
    check(c, "exp", ratio(arr(Numerics.exp(vec(x))), exp, relative(exp)))
    val log = c.values("log")
    check(c, "log", ratio(arr(Numerics.log(vec(c.values("p")))), log, relative(log)))
    val sigmoid = c.values("sigmoid")
    check(c, "sigmoid", ratio(arr(Numerics.sigmoid(vec(x))), sigmoid, relative(sigmoid)))
    val lse = c.scalar("logSumExp")
    check(c, "logSumExp", ratio(Numerics.logSumExp(vec(x)), lse, Eps * (math.abs(lse) + maxAbs(x) + n)))
    val softmax = c.values("softmax")
    check(
      c,
      "softmax",
      ratio(arr(Numerics.softmax(vec(x))), softmax, i => Eps * math.abs(softmax(i)) * (1 + math.abs(x(i)) + math.abs(lse) + n))
    )

  private def sparse(c: GoldenCase): Unit =
    val d = c.values("d")
    val n = d.length
    def sv(i: String, v: String) =
      SparseVector.fromEntries(n, c.values(i).map(_.toInt).toSeq.zip(c.values(v).toSeq))
    val x = sv("xi", "xv")
    val y = sv("yi", "yv")
    val xd = arr(x.toDense)
    val yd = arr(y.toDense)
    val s1 = sumAbs(xd)
    check(c, "dot", ratio(x.dot(y), c.scalar("dot"), n * Eps * xd.indices.map(i => math.abs(xd(i) * yd(i))).sum))
    check(c, "dotDense", ratio(x.dot(vec(d)), c.scalar("dotDense"), n * Eps * xd.indices.map(i => math.abs(xd(i) * d(i))).sum))
    check(c, "plus", ratio(arr((x + y).toDense), c.values("plus"), _ => 0.0))
    check(c, "minus", ratio(arr((x - y).toDense), c.values("minus"), _ => 0.0))
    check(c, "sum", ratio(x.sum, c.scalar("sum"), n * Eps * s1))
    check(c, "max", ratio(x.max, c.scalar("max"), 0.0))
    check(c, "min", ratio(x.min, c.scalar("min"), 0.0))
    check(c, "norm1", ratio(x.norm1, c.scalar("norm1"), n * Eps * s1))
    check(c, "norm2", ratio(x.norm2, c.scalar("norm2"), n * Eps * c.scalar("norm2")))
    check(c, "normInf", ratio(x.normInf, c.scalar("normInf"), 0.0))
