package gale.golden

import gale.golden.GoldenTolerance.*
import gale.linalg.*
import gale.sparse.SparseVector
import gale.spectral.*

import scala.collection.mutable

/** Replays the Breeze 2.1.0 golden corpus ([[BreezeGoldens]]) through gale's public API on the JVM and on
  * Scala.js. This is gale's only external-reference check of its Scala.js numerics; Breeze itself is JVM-only, so
  * the references are generated by `sbt breezeGoldens` (see `parity/README.md`).
  *
  * '''Tolerance policy.''' Never bit-exact: gale and Breeze use different algorithms and summation orders, and on
  * Scala.js `PlatformMath.fma` is `a*b+c`. Every check asserts `error ≤ C · unit` with one constant [[C]].
  *
  *   - '''Forward''' (gale vs Breeze): units from [[GoldenTolerance.forwardUnit]], shaped `n · κ · ε · scale`
  *     (`κ` = Breeze's 2-norm condition number for conditioning-sensitive results, `1` otherwise). Exact or
  *     correctly rounded operations (max/min/argmax/argmin, vector `normInf`, `kron`, sparse `+`/`−`) have unit
  *     `0` and must match exactly. Eigenvectors are compared through cluster projectors, unit `n ε ‖A‖ / gap`.
  *   - '''Backward''' (gale alone, κ-free): `‖b − A x̂‖∞ ≤ C n ε (‖A‖∞ ‖x̂‖∞ + ‖b‖∞)` for LU and Cholesky
  *     solves, `‖A X − I‖∞ ≤ C n ε ‖A‖∞ ‖X‖∞` for the inverse, `‖L Lᵀ − A‖max ≤ C n ε max a_ii` for Cholesky,
  *     and the normal-equations residual `‖Aᵀ r̂‖∞ ≤ C m ε ‖A‖₁ (‖A‖∞ ‖x̂‖∞ + ‖b‖∞ + ‖r̂‖∞)`, `r̂ = b − A x̂`,
  *     for least squares. The forward bounds are loose on ill-conditioned inputs; these catch a solver that loses
  *     digits there.
  *
  * The worst observed `error / unit` per family and output is printed after the suite, with the conditioned
  * (`kappa`, Hilbert, graded) cases listed separately.
  */
class BreezeGoldenSuite extends munit.FunSuite:

  /** The single tolerance constant multiplying every error unit. */
  private val C = 8.0

  private val worst = mutable.LinkedHashMap.empty[(String, Boolean), (Double, String)]

  private def conditioned(c: GoldenCase): Boolean =
    Seq("kappa", "hilbert", "graded").exists(c.name.contains)

  override def afterAll(): Unit =
    val platform = if System.getProperty("java.vm.name", "").contains("Scala.js") then "JS" else "JVM"
    println(s"BreezeGoldenSuite ($platform) worst error / unit by family and output (bound C = $C):")
    for (title, cond) <- Seq(("well-conditioned cases", false), ("conditioned cases (kappa, Hilbert, graded)", true))
    do
      println(s"  $title:")
      worst.toSeq
        .filter(_._1._2 == cond)
        .sortBy(_._1._1)
        .foreach { case ((k, _), (r, at)) => println(f"    $k%-28s $r%10.4f  ($at)") }

  // ---------------------------------------------------------------------------
  // Comparison helpers
  // ---------------------------------------------------------------------------

  private def check(c: GoldenCase, output: String, ratio: Double): Unit =
    val key = (s"${c.family}/$output", conditioned(c))
    if !worst.get(key).exists(_._1 >= ratio) then worst(key) = (ratio, c.name)
    assert(ratio <= C, s"${c.name}/$output: error is $ratio units (bound $C)")

  /** Worst `|g_i − ref_i| / unit(i)`; an exact match is `0` even when the unit is `0` or the value infinite. */
  private def ratio(g: Array[Double], ref: Array[Double], unit: Int => Double): Double =
    assertEquals(g.length, ref.length)
    var worstRatio = 0.0
    var i = 0
    while i < g.length do
      if g(i) != ref(i) then
        val r = math.abs(g(i) - ref(i)) / unit(i)
        worstRatio = if r.isNaN then Double.PositiveInfinity else math.max(worstRatio, r)
      i += 1
    worstRatio

  private def ratio(g: Double, ref: Double, unit: Double): Double = ratio(Array(g), Array(ref), _ => unit)

  /** Forward check of gale's `g` against Breeze reference `key`, in the shared units. */
  private def forward(c: GoldenCase, key: String, g: Array[Double]): Unit =
    check(c, key, ratio(g, c.values(key), forwardUnit(c, key)))

  private def forward(c: GoldenCase, key: String, g: Double): Unit = forward(c, key, Array(g))

  private def mat(a: GoldenArray): DMat = Matrix.tabulate(a.rows, a.cols)((i, j) => a(i, j))
  private def vec(a: Array[Double]): DVec = Vec.tabulate(a.length)(a(_))
  private def arr(v: DVec): Array[Double] = Array.tabulate(v.length)(v(_))
  private def arr(m: DMat): Array[Double] = Array.tabulate(m.rows * m.cols)(k => m(k / m.cols, k % m.cols))

  private def normInf(a: GoldenArray): Double =
    (0 until a.rows).map(i => (0 until a.cols).map(j => math.abs(a(i, j))).sum).max

  private def norm1(a: GoldenArray): Double =
    (0 until a.cols).map(j => (0 until a.rows).map(i => math.abs(a(i, j))).sum).max

  /** `b − A x` in plain double arithmetic. */
  private def residual(a: GoldenArray, x: Array[Double], b: Array[Double]): Array[Double] =
    Array.tabulate(a.rows) { i =>
      var s = b(i)
      for j <- 0 until a.cols do s -= a(i, j) * x(j)
      s
    }

  /** Backward check of a square solve: `‖b − A x̂‖∞ ≤ C n ε (‖A‖∞ ‖x̂‖∞ + ‖b‖∞)`. */
  private def backwardSolve(c: GoldenCase, x: Array[Double]): Unit =
    val a = c.array("A")
    val b = c.values("b")
    val unit = a.cols * Eps * (normInf(a) * maxAbs(x) + maxAbs(b))
    check(c, "solve-backward", ratio(maxAbs(residual(a, x, b)), 0.0, unit))

  // ---------------------------------------------------------------------------
  // Replay, one test per golden case
  // ---------------------------------------------------------------------------

  private val families = Set(
    "matvec",
    "matmul",
    "vector",
    "lu",
    "cholesky",
    "qr",
    "eigsym",
    "svd",
    "pinv",
    "kron",
    "reduce-vector",
    "reduce-matrix",
    "numerics",
    "sparse"
  )

  test("the golden corpus is non-empty and every family is known") {
    assert(BreezeGoldens.cases.nonEmpty)
    assertEquals(BreezeGoldens.cases.map(_.name).distinct.size, BreezeGoldens.cases.size)
    BreezeGoldens.cases.foreach(c => assert(families(c.family), s"unknown family ${c.family}"))
    assertEquals(BreezeGoldens.cases.map(_.family).toSet, families)
  }

  BreezeGoldens.cases.foreach(c => test(c.name)(replay(c)))

  private def replay(c: GoldenCase): Unit = c.family match
    case "matvec"        => matvec(c)
    case "matmul"        => matmul(c)
    case "vector"        => vector(c)
    case "lu"            => lu(c)
    case "cholesky"      => cholesky(c)
    case "qr"            => qr(c)
    case "eigsym"        => eigsym(c)
    case "svd"           => svd(c)
    case "pinv"          => pinv(c)
    case "kron"          => kron(c)
    case "reduce-vector" => reduceVector(c)
    case "reduce-matrix" => reduceMatrix(c)
    case "numerics"      => numerics(c)
    case "sparse"        => sparse(c)
    case other           => fail(s"unknown family $other")

  private def matvec(c: GoldenCase): Unit =
    val ga = mat(c.array("A"))
    forward(c, "Ax", arr(ga * vec(c.values("x"))))
    forward(c, "Atxt", arr(ga.t * vec(c.values("xt"))))

  private def matmul(c: GoldenCase): Unit =
    val ga = mat(c.array("A"))
    forward(c, "AB", arr(ga * mat(c.array("B"))))
    forward(c, "AtD", arr(ga.t * mat(c.array("D"))))

  private def vector(c: GoldenCase): Unit =
    val x = vec(c.values("x"))
    val y = vec(c.values("y"))
    forward(c, "dot", x.dot(y))
    val gy = y.mutableCopy
    gy.axpyInPlace(c.scalar("alpha"), x)
    forward(c, "axpy", arr(gy.asVec))

  private def lu(c: GoldenCase): Unit =
    val a = c.array("A")
    val n = a.rows
    val ga = mat(a)
    val x = arr(ga.solve(vec(c.values("b"))).orThrow)
    forward(c, "x", x)
    backwardSolve(c, x)
    forward(c, "det", ga.det.orThrow)
    if c.has("inv") then
      val inv = ga.solve(Matrix.eye(n)).orThrow
      forward(c, "inv", arr(inv))
      // ‖A X − I‖∞ ≤ C n ε ‖A‖∞ ‖X‖∞
      var resid = 0.0
      var normX = 0.0
      for i <- 0 until n do
        var row = 0.0
        var rowX = 0.0
        for j <- 0 until n do
          var s = if i == j then -1.0 else 0.0
          for k <- 0 until n do s += a(i, k) * inv(k, j)
          row += math.abs(s)
          rowX += math.abs(inv(i, j))
        resid = math.max(resid, row)
        normX = math.max(normX, rowX)
      check(c, "inv-backward", ratio(resid, 0.0, n * Eps * normInf(a) * normX))

  private def cholesky(c: GoldenCase): Unit =
    val a = c.array("A")
    val n = a.rows
    val factor = mat(a).cholesky.orThrow
    val gl = Array.tabulate(n * n)(p => if p % n <= p / n then factor.lower(p / n, p % n) else 0.0)
    forward(c, "L", gl)
    // ‖L Lᵀ − A‖max ≤ C n ε max a_ii  (|L||Lᵀ| is bounded entrywise by the diagonal of A)
    var recon = 0.0
    for i <- 0 until n; j <- 0 to i do
      var s = 0.0
      for k <- 0 to j do s += gl(i * n + k) * gl(j * n + k)
      recon = math.max(recon, math.abs(s - a(i, j)))
    val maxDiag = (0 until n).map(i => a(i, i)).max
    check(c, "L-backward", ratio(recon, 0.0, n * Eps * maxDiag))
    val x = arr(factor.solve(vec(c.values("b"))).orThrow)
    forward(c, "x", x)
    backwardSolve(c, x)

  private def qr(c: GoldenCase): Unit =
    val a = c.array("A")
    val (m, n) = (a.rows, a.cols)
    val gr = mat(a).qr.r
    val signs = Array.tabulate(n)(i => if gr(i, i) < 0.0 then -1.0 else 1.0)
    forward(c, "R", Array.tabulate(n * n)(p => if p % n >= p / n then signs(p / n) * gr(p / n, p % n) else 0.0))
    val b = c.values("b")
    val x = arr(mat(a).leastSquares(vec(b)).orThrow)
    forward(c, "x", x)
    // Normal-equations residual ‖Aᵀ r̂‖∞ ≤ C m ε ‖A‖₁ (‖A‖∞ ‖x̂‖∞ + ‖b‖∞ + ‖r̂‖∞): κ-free for a backward-stable x̂.
    val r = residual(a, x, b)
    val atr = Array.tabulate(n)(j => (0 until m).map(i => a(i, j) * r(i)).sum)
    val unit = m * Eps * norm1(a) * (normInf(a) * maxAbs(x) + maxAbs(b) + maxAbs(r))
    check(c, "lstsq-backward", ratio(maxAbs(atr), 0.0, unit))

  private def eigsym(c: GoldenCase): Unit =
    val a = c.array("A")
    val withVectors = c.has("vectors")
    val mode = if withVectors then EigenVectors.Right else EigenVectors.ValuesOnly
    val d = Eigen.eigSymmetric(mat(a), EigenSelection.All, mode).orThrow
    forward(c, "values", arr(d.eigenvalues))
    if withVectors then
      val ref = c.array("vectors")
      check(c, "vectors", projectorRatio(d.eigenvectors(_, _), ref(_, _), c.values("values")))

  private def svd(c: GoldenCase): Unit =
    forward(c, "sigma", arr(mat(c.array("A")).svd.orThrow.singularValues))

  private def pinv(c: GoldenCase): Unit =
    forward(c, "P", arr(mat(c.array("A")).pinv.orThrow))

  private def kron(c: GoldenCase): Unit =
    forward(c, "K", arr(mat(c.array("A")).kron(mat(c.array("B")))))

  private def reduceVector(c: GoldenCase): Unit =
    val v = vec(c.values("x"))
    forward(c, "sum", v.sum)
    forward(c, "mean", v.mean)
    forward(c, "max", v.max)
    forward(c, "min", v.min)
    forward(c, "argmax", v.argmax.toDouble)
    forward(c, "argmin", v.argmin.toDouble)
    forward(c, "norm1", v.norm1)
    forward(c, "norm2", v.norm2)
    forward(c, "normInf", v.normInf)

  private def reduceMatrix(c: GoldenCase): Unit =
    val g = mat(c.array("A"))
    forward(c, "sum", g.sum)
    forward(c, "mean", g.mean)
    forward(c, "max", g.max)
    forward(c, "min", g.min)
    val (i, j) = g.argmax
    forward(c, "argmaxRow", i.toDouble)
    forward(c, "argmaxCol", j.toDouble)
    forward(c, "frobenius", g.normFrobenius)
    forward(c, "norm1", g.norm1)
    forward(c, "normInf", g.normInf)

  private def numerics(c: GoldenCase): Unit =
    val x = vec(c.values("x"))
    forward(c, "exp", arr(Numerics.exp(x)))
    forward(c, "log", arr(Numerics.log(vec(c.values("p")))))
    forward(c, "sigmoid", arr(Numerics.sigmoid(x)))
    forward(c, "logSumExp", Numerics.logSumExp(x))
    forward(c, "softmax", arr(Numerics.softmax(x)))

  private def sparse(c: GoldenCase): Unit =
    val n = c.values("d").length
    def sv(i: String, v: String) =
      SparseVector.fromEntries(n, c.values(i).map(_.toInt).toSeq.zip(c.values(v).toSeq))
    val x = sv("xi", "xv")
    val y = sv("yi", "yv")
    forward(c, "dot", x.dot(y))
    forward(c, "dotDense", x.dot(vec(c.values("d"))))
    forward(c, "plus", arr((x + y).toDense))
    forward(c, "minus", arr((x - y).toDense))
    forward(c, "sum", x.sum)
    forward(c, "max", x.max)
    forward(c, "min", x.min)
    forward(c, "norm1", x.norm1)
    forward(c, "norm2", x.norm2)
    forward(c, "normInf", x.normInf)
